language: node_js
os:
#  - osx  TODO Enable again once we add openssl, libnice, libsrtp and libav to cmake
  - linux
sudo: required
dist: trusty
cache:
  directories:
  - node_modules
  - cache
  - build/libdeps
services:
  - mongodb
  - rabbitmq
addons:
  apt:
    packages:
      - git
      - make
      - gcc-5
      - g++-5
      - libssl-dev
      - cmake
      - libglib2.0-dev
      - pkg-config
      - libboost-regex-dev
      - libboost-thread-dev
      - libboost-system-dev
      - liblog4cxx10-dev
      - openjdk-6-jre
      - curl
      - libboost-test-dev
      - yasm
      - libvpx.
      - libx264.
    sources:
      - ubuntu-toolchain-r-test
before_install:
  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then   ./scripts/installMacDeps.sh --unattended --disable-services --use-cache;    fi

  # LINUX
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./scripts/travisInstallDeps.sh && export CC="/usr/bin/gcc-5" && export CXX="/usr/bin/g++-5" ; fi
install:
  - ./scripts/travisInstall.sh
script:
  - ./scripts/travisScript.sh
